[pytest]
testpaths = tests
addopts = -v -p no:html --junitxml=artifacts/junit.xml
log_cli = true
log_cli_level = INFO
log_file = artifacts/run.log
log_file_level = INFO
log_file_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s
